# DOCS: https://www.netlify.com/docs/netlify-toml-reference/

#[build]
#command = "npm i -gs yarn && yarn bootstrap && yarn build"

[[headers]]
# Define which paths this specific [[headers]] block will cover.
for = "/*"

[headers.values]
  X-Robots-Tag = "noindex" # We are in development phase
